@node External Protocols
@chapter External Protocols

@menu
* English Protocol::
* Word Protocol::
* Dictionary Protocol::
@end menu

This chapter describes the external protocols provided by the @sysname{} library.

@node English Protocol
@section English Protocol

This protocol provides the highest level of abstraction within the
@sysname{} library.  The protocol consists of a few functions that
perform the most common operations with minimal setup effort.

@deffuna{english-lookup,spell} (word)
Attempt to look up @var{word} in the English dictionary and return
either

@table @asis

@item @t{nil}
if no entry in the dictionary matches @var{word}

@item a single @t{word} object
if exactly one entry in the dictionary matches @var{word}

@item a list of @t{word} objects
if more than one entry in the dictionary matches @var{word}.  This case
of multiple words being returned happens when @var{word} can be
interpreted as multiple word types or multiple combinations of
properties within a word type.

@end table

Note that clients which are interested only in the validity of
@var{word} and not in the matching dictionary entries can treat the
return value as a generalized Boolean.
@end deffn

@deffuna{english-check-paragraph,spell} (string)
Check the paragraph of English text @var{string} for spelling errors and
return a list of detected errors.

The return value of this function is a possibly empty list of entries of
the form @t{(@var{start-index} . @var{end-index})}.  The
@var{start-index} and @var{end-index} within each entry designate a
sub-string of @var{string} that corresponds to a misspelled word.

For example, the following spell checking call
@lisp
(spell:english-check-paragraph "In Polish, a horse is koń, and in German, it's
das Pferd.")
@end lisp
results in the following three sub-strings that are not valid as English
words:
@example
((22 . 25) (47 . 50) (51 . 56))
@end example
@end deffn

@deffuna{english-corrections,spell} (string @pkey{} threshold)

If @var{string} is a word in the English dictionary, return @t{nil} and
otherwise return a list of strings that correspond to words in the
English dictionary that are at most @var{threshold} removed from
@var{string} in terms of edit-distance.

If supplied, @var{threshold} has to be a non-negative integer that
controls the maximum edit-distance of returned corrections from
@var{string}.  Note that the value @t{0} for @var{threshold} is not very
useful since @ref{Function spell|english-lookup,english-lookup} is a
simpler way to perform that operation.

Examples:
@lisp
(spell:english-corrections "lisp" :threshold 1)
@result{} NIL

(spell:english-corrections "lifp" :threshold 1)
@result{} ("lisp" "lip" "limp" "lift" "life")
@end lisp
@end deffn

@node Word Protocol
@section Word Protocol

The following class is the superclass for all word classes:

@defclassa{word,spell}
@end deftp

@defgena{base,spell} (word)
Return a string that is the base of @var{word}.
@end deffn

The @sysname{} library defines the following sub-classes of
@ref{Class spell|word,word}:

@include generated-word-classes.texi

@node Dictionary Protocol
@section Dictionary Protocol

@defgena{map-similar,spell} function string dictionary threshold

Call @var{function} for each entry in @var{dictionary} for which the
edit-distance to @var{string} is below @var{threshold}.  The entries are
reported in no particular order and in particular not ordered by
distance.

The lambda-list of @var{function} has to be compatible with
@t{(word spelling distance)} where @var{word} is the matching
@ref{Class spell|word,word} object, @var{spelling} is a string that is
the spelling of @var{word} (which is not obtainable from @var{word}
itself) and @var{distance} is the edit-distance between @var{word} and
@var{string}.

@var{string} is the query string and can be of any subtype of
@t{cl:string}.  At the moment, the case of string is left untouched and
only dictionary entries that match the case are reported.

@var{dictionary} is a dictionary.

@var{threshold} is a non-negative integer which controls how similar to
@var{string} in terms of edit-distance the reported entries have to be.

Example:
@lisp
(spell:map-similar
 (lambda (word spelling distance)
   (format t "~D ~10S ~A~%" distance spelling (class-name (class-of word)))))
 "lisp" spell::*english-dictionary* 1)
@print{} 1 "limp"     EXPLICIT-BASE-NOUN
@print{} 1 "limp"     EXPLICIT-BASE-ADJECTIVE
@print{} 1 "limp"     EXPLICIT-BASE-VERB
@print{} 1 "lip"      EXPLICIT-BASE-NOUN
@print{} 1 "lip"      EXPLICIT-BASE-VERB
@print{} 1 "lisps"    EXPLICIT-BASE-NOUN
@print{} 1 "lisps"    EXPLICIT-BASE-VERB
@print{} 0 "lisp"     EXPLICIT-BASE-NOUN
@print{} 0 "lisp"     EXPLICIT-BASE-VERB
@print{} 1 "list"     EXPLICIT-BASE-NOUN
@print{} 1 "list"     EXPLICIT-BASE-VERB
@print{} 1 "wisp"     EXPLICIT-BASE-NOUN
@print{} 1 "wisp"     EXPLICIT-BASE-VERB
@end lisp
@end deffn

@defgena{corrections,spell} string dictionary threshold

Examples:
@lisp
(spell:corrections "lisp" spell::*english-dictionary* 1)
@result{} NIL

(spell:corrections "lifp" spell::*english-dictionary* 1)
@result{} ("lisp" "lip" "limp" "lift" "life")
@end lisp
@end deffn
