\input texinfo

@include macros.texi
@include generated-version.texi

@documentencoding UTF-8
@documentlanguage en

@syncodeindex vr fn
@syncodeindex tp fn

@paragraphindent 0

@settitle @sysname{} User's Manual

@copying
This manual is for @sysname{} version @sysversion{}.

Copyright @copyright{} 2025 Jan Moringen
@end copying

@dircategory Common Lisp
@direntry
* spell User's Manual: (spell). A simple spell-checking library.
@end direntry

@titlepage
@title @sysname{} User's Manual

@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top @sysname{} User's Manual

@insertcopying
@end ifnottex

@menu
* Introduction::
* External Protocols::
* Concept index::
* Function and macro and variable and type index::
* Changelog::
@end menu

@include chapter-introduction.texi

@include chapter-external-protocols.texi

@node Concept index
@unnumbered Concept index

@printindex cp

@node Function and macro and variable and type index
@unnumbered Function and macro and variable and type index

@printindex fn

@include generated-chapter-changelog.texi

@bye
